# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac8ba37d739eaf47a5ff040ceb30e7f157562ee3a044a348abeadc2948a57aceb6711bbac82b391f64005bf67174b7fb6116d19ee24978ad80fe02522f12039

test:
  secret_key_base: 9bcdf0a54bdb57f031a14b9744eafc992eebf28965ed0738793254ddcaf1bdbeeee1c498426ea1cf785349f8f715c0c2c1d14cb65547745746a1d42108747345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
